import { VibescanConfig } from '../scanner/rules/types.js';

export const DEFAULT_CONFIG: VibescanConfig = {
  version: '1',
  include: ['src/**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}', 'app/**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}', '**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}'],
  exclude: [
    'node_modules/**',
    'dist/**',
    'build/**',
    '.next/**',
    'coverage/**',
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.spec.ts',
    '**/*.spec.tsx',
    '**/*.test.js',
    '**/*.spec.js',
    '**/*.d.ts',
  ],
  rules: {
    'security/hardcoded-secrets': 'error',
    'security/command-injection': 'error',
    'security/code-injection': 'error',
    'security/sql-injection': 'error',
    'security/xss-vulnerabilities': 'error',
    'security/open-redirect': 'error',
    'security/insecure-deserialization': 'error',
    'security/xxe-injection': 'error',
    'security/eval-usage': 'error',
    'security/weak-crypto': 'error',
    'security/jwt-no-expiry': 'error',
    'security/jwt-unsafe-verify': 'error',
    'security/missing-rate-limit': 'warn',
    'security/path-traversal': 'error',
    'security/ssrf-risk': 'error',
    'security/cors-misconfiguration': 'error',
    'security/prototype-pollution': 'error',
    'security/regex-dos': 'warn',
    'security/nosql-injection': 'error',
    'security/csrf-missing': 'warn',
    'security/insecure-session': 'warn',
    'ai-smell/dead-code-blocks': 'warn',
    'ai-smell/inconsistent-error-handling': 'warn',
    'ai-smell/todo-stub-functions': 'warn',
    'ai-smell/hallucinated-api-calls': 'error',
    'ai-smell/copy-paste-patterns': 'warn',
    'ai-smell/missing-null-checks': 'warn',
    'ai-smell/debug-leftovers': 'info',
    'ai-smell/mixed-async-patterns': 'warn',
    'ai-smell/magic-numbers': 'info',
    'ai-smell/generic-variable-names': 'info',
    'ai-smell/ai-confidence-scorer': 'info',
    'tech-debt/cyclomatic-complexity': 'warn',
    'tech-debt/function-length': 'warn',
    'tech-debt/nesting-depth': 'warn',
    'tech-debt/god-files': 'warn',
    'tech-debt/hardcoded-config': 'warn',
    'tech-debt/missing-types': 'warn',
  },
  thresholds: {
    maxErrors: 0,
    maxWarnings: 20,
    minAIScore: 60,
  },
  output: {
    format: 'terminal',
    htmlReportPath: '.aicop/report.html',
  },
  testPatterns: ["**/*.test.{js,ts,jsx,tsx}", "**/*.spec.{js,ts,jsx,tsx}", "**/__tests__/**", "**/test/**/*", "**/tests/**/*", "**/fixtures/**/*"],
  testOverrides: {
    "security/hardcoded-secrets": "warn",
    "security/eval-usage": "warn",
    "ai-smell/todo-stub-functions": "off",
    "ai-smell/missing-null-checks": "off",
    "ai-smell/copy-paste-patterns": "off",
    "security/xss-vulnerabilities": "warn",
    "security/regex-dos": "warn",
    "security/missing-rate-limit": "off",
    "security/open-redirect": "off",
    "security/cors-misconfiguration": "off"
  }
};
