import { VibescanConfig } from '../scanner/rules/types.js';

export const DEFAULT_CONFIG: VibescanConfig = {
  version: '1',
  include: ['src/**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}', 'app/**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}', '**/*.{ts,tsx,js,jsx,mjs,cjs,mts,cts}'],
  exclude: [
    'node_modules/**',
    'dist/**',
    'build/**',
    '.next/**',
    'coverage/**',
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.spec.ts',
    '**/*.spec.tsx',
    '**/*.test.js',
    '**/*.spec.js',
    '**/*.min.js',
    '**/*.bundle.js',
    '**/*.d.ts',
  ],
  rules: {
    'security/hardcoded-secrets': 'error',
    'security/sql-injection': 'error',
    'security/xss-vulnerabilities': 'error',
    'security/eval-usage': 'error',
    'security/weak-crypto': 'error',
    'security/jwt-no-expiry': 'error',
    'security/missing-rate-limit': 'warn',
    'security/path-traversal': 'error',
    'security/ssrf-risk': 'error',
    'security/cors-misconfiguration': 'error',
    'security/prototype-pollution': 'error',
    'security/regex-dos': 'warn',
    'ai-smell/dead-code-blocks': 'warn',
    'ai-smell/inconsistent-error-handling': 'warn',
    'ai-smell/todo-stub-functions': 'warn',
    'ai-smell/hallucinated-api-calls': 'error',
    'ai-smell/copy-paste-patterns': 'warn',
    'ai-smell/missing-null-checks': 'warn',
    'ai-smell/debug-leftovers': 'info',
    'ai-smell/mixed-async-patterns': 'warn',
    'ai-smell/magic-numbers': 'info',
    'ai-smell/generic-variable-names': 'info',
    'ai-smell/ai-confidence-scorer': 'info',
    'tech-debt/cyclomatic-complexity': 'warn',
    'tech-debt/function-length': 'warn',
    'tech-debt/nesting-depth': 'warn',
    'tech-debt/god-files': 'warn',
    'tech-debt/hardcoded-config': 'warn',
    'tech-debt/missing-types': 'warn',
  },
  thresholds: {
    maxErrors: 0,
    maxWarnings: 20,
    minVibeScore: 60,
  },
  output: {
    format: 'terminal',
    htmlReportPath: '.vibescan/report.html',
  },
};
