import { Rule, Finding, ParsedAST } from '../types.js';
import { walk } from '../../ast-walker.js';
import { extractSnippet } from '../../../utils/file-utils.js';
import { getLine, getColumn } from '../../../utils/ast-helpers.js';

const rule: Rule = {
  id: 'ai-smells/unused-imports',
  name: 'unused imports',
  category: 'ai-smell',
  severity: 'info',
  description: 'Detects unused imports',
  why: 'This is a common pattern generated by AI that should be refactored.',
  fix: 'Refactor to adhere to best practices.',

  check(ast: ParsedAST, source: string, filePath: string): Finding[] {
    const findings: Finding[] = [];
    walk(ast, {
      enter(_node) {
        // Implement logic here
      },
    });
    return findings;
  },
};

export default rule;
